---
# generated by https://github.com/hashicorp/terraform-plugin-docs
page_title: "k3d_cluster_action Resource - terraform-provider-k3d"
subcategory: ""
description: |-
  
---

# k3d_cluster_action (Resource)
Helps in stopping or stating a specific cluster ot a list of clusters

```terraform
resource "k3d_cluster_action" "start-k3s-cluster" {
    depends_on = [
    k3d_cluster_action.stop-k3s-cluster,
    ]
    clusters = ["k3s-default"]
    start    = true
}
```




<!-- schema generated by tfplugindocs -->
## Schema

### Optional

- `all` (Boolean) if enabled selected clusters would be started/stopped
- `clusters` (List of String) list of k3s clusters on which the action has to be applied
- `start` (Boolean) if enabled it starts a stopped cluster
- `state` (String) latest state of selected clusters
- `status` (Block List) updated status of clusters (see [below for nested schema](#nestedblock--status))
- `stop` (Boolean) if enabled it stops a running cluster
- `timeouts` (Block, Optional) (see [below for nested schema](#nestedblock--timeouts))

### Read-Only

- `id` (String) The ID of this resource.

<a id="nestedblock--status"></a>
### Nested Schema for `status`

Optional:

- `agents_count` (Number) count of agents in the cluster
- `agents_running` (Number) number of agents running in the cluster
- `cluster_token` (String) token of the cluster
- `has_loadbalancer` (Boolean) attribute that notifies the presence of loadbalancer in the cluster
- `image_volume` (String) volume to import images
- `name` (String) cluster name that was fetched
- `network` (String) network associated with the cluster
- `nodes` (List of String) list of nodes present in cluster
- `servers_count` (Number) count of servers
- `servers_running` (Number) count of servers running


<a id="nestedblock--timeouts"></a>
### Nested Schema for `timeouts`

Optional:

- `create` (String)
- `delete` (String)
- `update` (String)


