---
# generated by https://github.com/hashicorp/terraform-plugin-docs
page_title: "k3d_connect_registry Resource - terraform-provider-k3d"
subcategory: ""
description: |-
  
---

# k3d_connect_registry (Resource)
Connects or disconnects already created registry from the specified cluster.

```terraform
resource "k3d_connect_registry" "k3s-registry-1" {
    registries = [k3d_create_registry.registry-1.host]
    cluster    = "k3s-default"
    connect    = true
}
```


<!-- schema generated by tfplugindocs -->
## Schema

### Required

- `cluster` (String) cluster to which registries to be associated with
- `connect` (Boolean) enable this flag if registries to be connected with specified cluster
- `registries` (List of String) list of registries to be connected to the selected cluster

### Optional

- `status` (Block List) updated status of registry (see [below for nested schema](#nestedblock--status))

### Read-Only

- `id` (String) The ID of this resource.

<a id="nestedblock--status"></a>
### Nested Schema for `status`

Optional:

- `cluster` (String) cluster to which the registry is either connected/disconnected
- `registry` (String) name of the registry
- `state` (String) updated state of registry


