---
# generated by https://github.com/hashicorp/terraform-plugin-docs
page_title: "k3d_node_action Resource - terraform-provider-k3d"
subcategory: ""
description: |-
  
---

# k3d_node_action (Resource)
Helps in starting or stopping a specific node or list of nodes which are part of the cluster

```terraform
resource "k3d_node_action" "k3s-default-3" {
    nodes   = ["k3d-k3s-default-agent-0", "k3d-k3s-default-agent-1"]
    cluster = "k3s-default"
    stop    = true
}
```




<!-- schema generated by tfplugindocs -->
## Schema

### Required

- `cluster` (String) name of the cluster of which that nodes to be acted upon

### Optional

- `all` (Boolean) if enabled fetches all the nodes available in the selected cluster
- `nodes` (List of String) list of nodes on which the action has to be applied
- `start` (Boolean) if enabled it starts a stopped nodes
- `status` (Block List) updated status of started/stopped nodes (see [below for nested schema](#nestedblock--status))
- `stop` (Boolean) if enabled it stops a running nodes
- `timeouts` (Block, Optional) (see [below for nested schema](#nestedblock--timeouts))

### Read-Only

- `id` (String) The ID of this resource.

<a id="nestedblock--status"></a>
### Nested Schema for `status`

Required:

- `cluster` (String) name of the cluster of to which node belongs

Read-Only:

- `node` (String) node of which the current status is updated with
- `role` (String) role of updated node
- `state` (String) current state of the node specified


<a id="nestedblock--timeouts"></a>
### Nested Schema for `timeouts`

Optional:

- `create` (String)
- `delete` (String)
- `update` (String)


