---
# generated by https://github.com/hashicorp/terraform-plugin-docs
page_title: "k3d_node_create Resource - terraform-provider-k3d"
subcategory: ""
description: |-
  
---

# k3d_node_create (Resource)
Creates a K3D node with all specified configurations under a specified node. This resource is an implementation of k3d cli's `k3d node create`.

```terraform
resource "k3d_node_create" "node-1" {
    name     = "sample-node-2"
    cluster  = k3d_cluster_create.sample_cluster.name
    role     = "agent"
    replicas = 1
    #  memory   = "8g"
    //  wait     = false
    //  timeout  = 1
}
```


<!-- schema generated by tfplugindocs -->
## Schema

### Required

- `cluster` (String) name of the cluster to which these nodes to be connected with
- `name` (String) name the nodes to be created (index would be used to dynamically compute the names for nodes)

### Optional

- `creation_time` (String) timestamp of nodes creation, this would be used to track the nodes created
- `image` (String) image to be used for nodes creation defaults to image declared in provider
- `memory` (String) memory limit to be imposed on the node
- `replicas` (Number) number of nodes to be created
- `role` (String) role to be assigned to the node(agent)
- `timeout` (Number) maximum waiting time for before canceling/returning in minutes
- `wait` (Boolean) if enabled waits for nodes to be ready before returning

### Read-Only

- `id` (String) The ID of this resource.
- `nodes` (List of Object) list of nodes that were created (see [below for nested schema](#nestedatt--nodes))

<a id="nestedatt--nodes"></a>
### Nested Schema for `nodes`

Read-Only:

- `cluster` (String)
- `created` (String)
- `env` (List of String)
- `image` (String)
- `memory` (String)
- `name` (List of String)
- `networks` (List of String)
- `role` (String)
- `state` (String)
- `volumes` (List of String)


