---
# generated by https://github.com/hashicorp/terraform-plugin-docs
page_title: "rancherk3d_connect_registry Resource - terraform-provider-k3d"
subcategory: ""
description: |-
  
---

# rancherk3d_connect_registry (Resource)





<!-- schema generated by tfplugindocs -->
## Schema

### Required

- `cluster` (String) cluster to which registries to be associated with
- `connect` (Boolean) enable this flag if registries to be connected with specified cluster
- `registries` (List of String) list of registries to be connected to the selected cluster

### Optional

- `status` (Block List) updated status of registry (see [below for nested schema](#nestedblock--status))

### Read-Only

- `id` (String) The ID of this resource.

<a id="nestedblock--status"></a>
### Nested Schema for `status`

Optional:

- `cluster` (String) cluster to which the registry is either connected/disconnected
- `registry` (String) name of the registry
- `state` (String) updated state of registry


