---
# generated by https://github.com/hashicorp/terraform-plugin-docs
page_title: "rancherk3d_create_registry Resource - terraform-provider-k3d"
subcategory: ""
description: |-
  
---

# rancherk3d_create_registry (Resource)





<!-- schema generated by tfplugindocs -->
## Schema

### Required

- `name` (String) name the registry node to be created

### Optional

- `cluster` (String) cluster to which the registry to be associated with
- `config_file` (String) config file to be used for configuring registry
- `expose` (Map of String) host to port mapping
- `host` (String) host name to be assigned to the registry the would be created (defaults to name of registry)
- `image` (String) image to be used for creation of registry
- `protocol` (String) protocol to be used while running registry (defaults to http)
- `proxy` (Map of String) proxy configurations to be used while configuring registry if enabled
- `registries_list` (Block List) list of registries those were created (see [below for nested schema](#nestedblock--registries_list))
- `use_proxy` (Boolean) if enabled proxy config provided at 'proxy' would be used for configuring registry

### Read-Only

- `id` (String) The ID of this resource.

<a id="nestedblock--registries_list"></a>
### Nested Schema for `registries_list`

Optional:

- `cluster` (String) cluster to which the registry belongs
- `created` (String) creation timestamp of registry node
- `env` (List of String) environment variables set in the node
- `image` (String) image used for registry
- `name` (List of String) name of the registry
- `networks` (List of String) networks associated with the registries
- `port_mappings` (Map of String) port mappings
- `role` (String) role of registry created/retrieved
- `state` (String) current state of registry node


