---
# generated by https://github.com/hashicorp/terraform-plugin-docs
page_title: "k3d_cluster Data Source - terraform-provider-k3d"
subcategory: ""
description: |-
  
---

# k3d_cluster (Data Source)





<!-- schema generated by tfplugindocs -->
## Schema

### Required

- `clusters` (List of String) list of clusters of which the information to be fetched

### Optional

- `all` (Boolean) if enabled fetches all clusters available

### Read-Only

- `clusters_list` (List of Object) list of cluster of which information has been retrieved (see [below for nested schema](#nestedatt--clusters_list))
- `id` (String) The ID of this resource.

<a id="nestedatt--clusters_list"></a>
### Nested Schema for `clusters_list`

Read-Only:

- `agents_count` (Number)
- `agents_running` (Number)
- `cluster_token` (String)
- `has_loadbalancer` (Boolean)
- `image_volume` (String)
- `name` (String)
- `network` (String)
- `nodes` (List of String)
- `servers_count` (Number)
- `servers_running` (Number)


