---
# generated by https://github.com/hashicorp/terraform-plugin-docs
page_title: "rancherk3d_kubeconfig Data Source - terraform-provider-k3d"
subcategory: ""
description: |-
  
---

# rancherk3d_kubeconfig (Data Source)





<!-- schema generated by tfplugindocs -->
## Schema

### Optional

- `all` (Boolean) set this if kube-config has to be fetched from all available k3s clusters
- `clusters` (List of String) list of k3s clusters from which the kube-config has to be retrieved
- `kube_config` (Map of String, Sensitive) retrieved kube-config for the specified cluster
- `not_encoded` (Boolean) set it to false if base64 encoding of kube-config is not preferred, defaults to true

### Read-Only

- `id` (String) The ID of this resource.


