remote_theme: pmarsceill/just-the-docs
theme: just-the-docs
title: rancherk3d provider
heading_anchors: true
back_to_top: true
back_to_top_text: "Go Back to top"
url: "https://nikhilsbhat.github.io/"
permalink: pretty

search:
  heading_level: 2
  previews: 3
  preview_words_before: 2
  preview_words_after: 3
  rel_url: false
  button: true
  tokenizer_separator: /[\s\-/]+/


aux_links:
  "terraform-provider-rancherk3d on GitHub":
    - "//github.com/nikhilsbhat/terraform-provider-rancherk3d"
aux_links_new_tab: true

footer_content: "Copyright &copy; 2020-2021 Nikhil Bhat. Distributed by an <a href=\"https://github.com/nikhilsbhat/terraform-provider-rancherk3d/blob/master/LICENSE\">MIT license.</a>"
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/nikhilsbhat/terraform-provider-rancherk3d"
gh_edit_branch: "master"
gh_edit_source: docs
gh_edit_view_mode: "tree"
